<?php
// PHPetite v.0.1 (Based off the excellent work of Portable PHP)
// Render each of the Markdown files from a folder in a <section>, with date-and-title as #id.

include '_system.php';
// $site_info takes all forms of HTML. Leave blank if you just want blog posts on the homepage
$site_info = '<div class="site-info">' . $parsedown->text(file_get_contents('content/_pages/home-content.md')) .'</div>';

?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title><?php echo $site_title; ?></title>
  <meta name="description" content="<?php echo $site_desc; ?>">
  <link rel="icon" href="data:image/png;base64,<?php echo base64_encode(file_get_contents($site_icon)); ?>">
  <!-- og tags -->
  <meta property="og:title" content="<?php echo $site_title; ?>">
  <meta property="og:description" content="<?php echo $site_desc; ?>">
  <!-- other -->
  <meta name="twitter:card" content="summary">
  <style>
    <?php
        $cssFiles = array(
          "style.css"
        );

        $buffer = "";
        foreach ($cssFiles as $cssFile) {
          $buffer .= file_get_contents($cssFile);
        }
        $buffer = preg_replace('!/\*[^*]*\*+([^/][^*]*\*+)*/!', '', $buffer);
        $buffer = str_replace(': ', ':', $buffer);
        $buffer = str_replace(array("\r\n", "\r", "\n", "\t", '  ', '    ', '    '), '', $buffer);
        echo($buffer);
    ?>
  </style>
</head>
<body>
  <header>
    <h1>
      <a href="#home"><?php echo $site_title; ?></a>
    </h1>
  </header>
  <main>
    <?php echo $posts; ?>
    <?php echo $pages; ?>
    <section tabindex="0" role="document" aria-label="Home" id="home">
      <?php 
        if ($site_info != '') {
          echo $site_info;
          echo '<hr>';
        }
      ?>
      <nav>
        <ul class="toc">
          <?php echo $toc; ?>
        </ul>
      </nav>
    </section>
  </main>
  <footer>
    <small>Last updated on <?php echo date("F j, Y"); ?></small>
    <div class="footer-links">
        <small><?php echo $pages_footer; ?></small>
    </div>
  </footer>
<!--  generated by PHPetite
      <?php echo date("l jS \of F Y h:i:s A"); ?>
      execution time: <?php echo $executionTime = microtime(true) - $_SERVER["REQUEST_TIME_FLOAT"]; ?> seconds -->
</body>
</html>